import { Application, Evidence } from './types';

export const seedApps: Application[] = [
  {
    id: 'seed-app-1',
    userId: 'demo-user',
    school: 'Northbridge University',
    program: 'Computer Science — Early Action',
    applicationStatus: 'preparing',
    deadline: '2026-08-31',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    requirements: [
      { id: 'req-1', name: 'Academic transcript', status: 'done', category: 'Document' },
      { id: 'req-2', name: 'Personal statement', status: 'review', category: 'Essay' },
      { id: 'req-3', name: 'Recommendation letter', status: 'missing', category: 'Recommendation' },
      { id: 'req-4', name: 'Passport photo', status: 'done', category: 'Document' },
      { id: 'req-5', name: 'Application fee', status: 'missing', category: 'Payment' },
    ],
  },
  {
    id: 'seed-app-2',
    userId: 'demo-user',
    school: 'Future Leaders Foundation',
    program: 'Global Scholarship 2026',
    applicationStatus: 'in_progress',
    deadline: '2026-09-05',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    requirements: [
      { id: 'req-21', name: 'Academic transcript', status: 'done', category: 'Document' },
      { id: 'req-22', name: 'Leadership essay', status: 'missing', category: 'Essay' },
      { id: 'req-23', name: 'Achievement evidence', status: 'done', category: 'Evidence' },
      { id: 'req-24', name: 'Recommendation letter', status: 'missing', category: 'Recommendation' },
    ],
  },
  {
    id: 'seed-app-3',
    userId: 'demo-user',
    school: 'LaunchLab Fellowship',
    program: 'Student Builder Track',
    applicationStatus: 'ready',
    deadline: '2026-09-12',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    requirements: [
      { id: 'req-31', name: 'Project demo', status: 'done', category: 'Project' },
      { id: 'req-32', name: 'Founder statement', status: 'done', category: 'Essay' },
      { id: 'req-33', name: 'CV', status: 'done', category: 'Document' },
      { id: 'req-34', name: 'Interview availability', status: 'review', category: 'Interview' },
    ],
  },
];

export const seedEvidence: Evidence[] = [
  {
    id: 'seed-ev-1',
    userId: 'demo-user',
    title: 'Competitive Futsal',
    org: '8+ years of competitive play',
    category: 'Leadership',
    tags: ['discipline', 'teamwork', 'sport'],
    description: 'Long-term competitive team sport experience demonstrating consistency and teamwork.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-ev-2',
    userId: 'demo-user',
    title: 'Tournament Management',
    org: 'Managed competitive futsal events',
    category: 'Leadership',
    tags: ['operations', 'leadership', 'events'],
    description: 'Coordinated competitive tournaments, teams, schedules and event operations.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-ev-3',
    userId: 'demo-user',
    title: 'STEM Exhibition',
    org: 'School STEM delegation',
    category: 'Technology',
    tags: ['innovation', 'technology', 'teamwork', 'stem'],
    description: 'Built and presented a project as part of a school STEM delegation.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-ev-4',
    userId: 'demo-user',
    title: 'Harvard CS Coursework',
    org: 'Computer science coursework',
    category: 'Academic',
    tags: ['cs', 'programming', 'learning'],
    description: 'Completed structured computer science study with programming fundamentals.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
